# Generated by cucumber-sinatra. (2015-11-17 18:11:22 -0500)

ENV['RACK_ENV'] = 'test'

require 'rspec'
require 'conjur/api'
require 'conjur/cli'

$LOAD_PATH.unshift File.expand_path('lib', File.dirname(__FILE__))

$service_url = ENV['CONJUR_APPLIANCE_URL'] || "https://localhost/api"

Conjur::Config.load
Conjur::Config.apply

# require 'ws'
